version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: LordITrustInYou1!
      MYSQL_DATABASE: titlebot_db
    networks:
      springboot-mysql-net:

  springboot-restful-titlebot:
    container_name: springboot-restful-titlebot
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

  react-app:
    container_name: react-app
    build:
      context: ../react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      springboot-mysql-net:


networks:
  springboot-mysql-net:


